version = "3.7.15"
runner.dialect = scala213
fileOverride {
  "glob:**/build.sc/**" {
     runner.dialect = scala3
  }
  "glob:**/out/mill-bsp-out/mill-build/generatedScriptSources.dest/support/**" {
     runner.dialect = scala3
  }
  "glob:**/mill-build/src/**" {
     runner.dialect = scala3
  }
}
